package com.sample

import java.util.ArrayList;

rule "ask"
	when e : WineChooser.Exchange(e.getAnswer().equals(""));
	then
		String answer = WineChooser.userInterface.waitForAnswer();
		WineChooser.Exchange ex = new WineChooser.Exchange(e.getQuestion(), e.getAnswer());
		insert(ex);
end

rule "init_the_rule_system"
    when
    then
        WineChooser.Exchange e = new WineChooser.Exchange("Who will be drinking the wine?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Someone else");
    	answers.add("Personal use");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(e);
        insert(e);
end

rule "Q1A" 
	when 
		e : WineChooser.Exchange(e.getQuestion().equals("Who will be drinking the wine?") && e.getAnswer().equals("Someone else") );
	then
		WineChooser.Exchange ex = new WineChooser.Exchange("Are you at a social gathering?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q1B" 
	when 
		e : WineChooser.Exchange(e.getQuestion().equals("Who will be drinking the wine?") && e.getAnswer().equals("Personal use") );
	then
		WineChooser.Exchange ex = new WineChooser.Exchange("Are you at home?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q2A" 
	when 
		e : WineChooser.Exchange(e.getQuestion().equals("Are you at a social gathering?") && e.getAnswer().equals("Yes") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("What type?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Art opening");
    	answers.add("Beach barbeque");
    	answers.add("Dinner party");
    	answers.add("Bachelor party");
    	answers.add("Get together");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q2B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you at a social gathering?") && e.getAnswer().equals("No") );
	then
		//Are they a wine lover? < - nie wiem o co tu chodzi, ten komentarz nie wiem do czego jest
		WineChooser.Exchange ex = new WineChooser.Exchange("Is it a gift?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q3A"  
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you at home?") && e.getAnswer().equals("Yes") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are you alone?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q3B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you at home?") && e.getAnswer().equals("No") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are you on the go?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Dinner");
    	answers.add("Restaurant");
    	answers.add("Camping");
    	answers.add("Drinking in public");
    	answers.add("Special occasions");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q4A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type?") && e.getAnswer().equals("Art opening") );
	then
		WineChooser.userInterface.finishChoosing("2-buck chuck");
		WineChooser.Exchange ex = new WineChooser.Exchange("they rarely have a sense of taste", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q4B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type?") && e.getAnswer().equals("Beach barbeque") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("bought a nice bottle but it was confiscated. no glass on the beach", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q4C" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type?") && e.getAnswer().equals("Dinner party") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Who is cooking?"", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Them");
    	answers.add("Me");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q4D" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type?") && e.getAnswer().equals("Bachelor party") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("leave your wine at home. bring whiskey or vodka", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q4E" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type?") && e.getAnswer().equals("Get together") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Do you know them?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q5A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it a gift?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Do you really know them?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q5B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it a gift?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("They don't deserve wine. Get out of my flow-chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q6A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Who is cooking?") && e.getAnswer().equals("Me") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("They don't deserve wine. Get out of my flow-chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q6B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Who is cooking?") && e.getAnswer().equals("Them") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Buy the biggest bottle with the words 'red blend'.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q7A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Do you know them?") && e.getAnswer().equals("Yes") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are they wine lovers?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q7B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Do you know them?") && e.getAnswer().equals("No") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Bring a boring bottle and hope no one opens it.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q8A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are they win lovers?") && e.getAnswer().equals("Yes") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are they your favorite people in the world?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("No");
    	answers.add("Be honest");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q8B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are they wine lovers?") && e.getAnswer().equals("No") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("They don't deserve wine. Get out of my flow-chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q9A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Do you really know them?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are they your favorite people in the world?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("No");
    	answers.add("Be honest");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q9B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Do you really know them?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("They don't deserve wine. Get out of my flow-chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q10A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are they your favorite people in the world?") && e.getAnswer().equals("Be honest") ); 
	then
		//new panel 
		//Yes.
		
		// ^ nie wiem co tutaj :(
end 

rule "Q10B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are they your favorite people in the world?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("They don't deserve wine. Get out of my flow-chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q10C" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are they your favorite people in the world?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Hedonistic joy ride california pinot noir", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q11A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you alone?") && e.getAnswer().equals("Yes") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Recovering from work?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q11B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you alone?") && e.getAnswer().equals("No") );
	then
		//newExchange("How about?");
		//Dinner.
		
		// ^ nie iwem jak to zbudować :(
end 

rule "Q12A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Recovering from work?") && e.getAnswer().equals("Yes") );
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Sniff your glass of pinot noir", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q12B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Recovering from work?") && e.getAnswer().equals("No") );
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Getting drunk?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q13A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Getting drunk?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Zinfandel or shiraz", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q13B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Getting drunk?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Feeling fancy?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Oui");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q14A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Feeling fancy?") && e.getAnswer().equals("Oui") ); 
	then
		WineChooser.userInterface.finishChoosing("sangiovese or grenache");
		WineChooser.Exchange ex = new WineChooser.Exchange("Go for something exotic", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q14B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Feeling fancy?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Daily drinking wine?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q15A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Daily drinking wine?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are you a kool-aid man?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q15B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Daily drinking wine?") && e.getAnswer().equals("No") ); 
	then
		//newExchange("What for then?"); 
		//For my wine collection.
		
		// ^ nie wiem co tu :(
end 



rule "Q16A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you a kool-aid man?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing("argentinian malbec");
		WineChooser.Exchange ex = new WineChooser.Exchange("fruit forward wine", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q16B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you a kool-aid man?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Did you eat dirt as a child?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yum");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q17A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Did you eat dirt as a child?") && e.getAnswer().equals("Yum") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Something earthy chinon or bourgueil", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q17B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Did you eat dirt as a child?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Did you spray butter in your mouth?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yep");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q18A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Did you spray butter in your mouth?") && e.getAnswer().equals("Yep") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Please bring me my buttery chardonnay.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q18B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Did you spray butter in your mouth?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Thx for playing' now get out of my flow chart.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q19A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What for then?") && e.getAnswer().equals("For my wine collection") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("New vs. old world", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	answers.add("What?");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q20A" 
	when
		e : WineChooser.Exchange( (e.getQuestion().equals("How about?") || e.getQuestion().equals("Are you on the go?")) && e.getAnswer().equals("Dinner") ); 
	then
		//newExchange("Are you sure about the dinner?");
		//Yes.
		
		// ^ nie wiem co tu :(
end 

rule "Q20B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you on the go?") && e.getAnswer().equals("Restaurant") ); 
	then
		//newExchange("Is it fancy?");
		//Yes // not this Can you pronounce the menu?
		//No.
		
		// nie wiem co tutaj :(
end 

rule "Q20C" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you on the go?") && e.getAnswer().equals("Camping") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("/No cork screw required, single serve box wine", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q20D" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you on the go?") && e.getAnswer().equals("Drinking in public") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("/No cork screw required, single serve box wine", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q21" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you sure about the dinner?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Is wine the main course?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q22A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is wine the main course?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing("sangiovese or grenache");
		WineChooser.Exchange ex = new WineChooser.Exchange("Go for something exotic", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q22B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is wine the main course?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Dinner from a microwave?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q23A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Dinner from a microwave?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("Go buget. Go bulk. 3 liter box wine.", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q23A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Dinner from a microwave?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Do you cook with your wine?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q24A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Dou you cok with your wine?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing("sauvignon blanc");
		WineChooser.Exchange ex = new WineChooser.Exchange("White 9 dollar such as", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q24B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Dou you cok with your wine?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are you a kool-aid man?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q25A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it fancy?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Can you pronounce the menu?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q25B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it fancy?") && e.getAnswer().equals("No") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Is it an order trom a window?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes..?");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q26A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Can you pronounce the menu?") && e.getAnswer().equals("Yes") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("New vs. old world", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("What?");
    	answers.add("Old!");
    	answers.add("New");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q26B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Can you pronounce the menu?") && e.getAnswer().equals("No") ); 
	then
		//ask for cotes du rhone.
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("ask for cotes du rhone", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 



rule "Q27A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it an order trom a window?") && e.getAnswer().equals("Yes..?") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("go buget go bulk 3 liter box wine", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q27B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is it an order trom a window?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing("sun california cabernet");
		WineChooser.Exchange ex = new WineChooser.Exchange("drink a botle of", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 



rule "Q28A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("New vs. old world.") && e.getAnswer().equals("What?") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("thx for playing gettouta my flowchart smth", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q28B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("New vs. old world.") && e.getAnswer().equals("Old!") ); 
	then
		WineChooser.userInterface.finishChoosing(null;
		WineChooser.Exchange ex = new WineChooser.Exchange("why but anything but bordeaux or burgundy", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q28C" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("New vs. old world.") && e.getAnswer().equals("New") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Are you into cults?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 



rule "Q29A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you into cults?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("cult classic sine qua non or cayuse", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q29B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you into cults?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing("sun california cabernet");
		WineChooser.Exchange ex = new WineChooser.Exchange("drink a bottle of", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q30" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Are you on the go?") && e.getAnswer().equals("Special occasions") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("What type of special occasion?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Anniversary");
    	answers.add("Eloping");
    	answers.add("Birthday");
    	answers.add("Blind date");
    	answers.add("New Year's Eve");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q31A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type of special occasion?") && e.getAnswer().equals("Anniversary") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("First or subsequent", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("1st");
    	answers.add("2+");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q31B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type of special occasion?") && e.getAnswer().equals("Eloping") ); 
	then
		WineChooser.userInterface.finishChoosing("Something sweet");
		WineChooser.Exchange ex = new WineChooser.Exchange("riesling or chenin blanc", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q31C" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type of special occasion?") && e.getAnswer().equals("Birthday") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("Is the person old?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 

rule "Q31D" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type of special occasion?") && e.getAnswer().equals("Blind date") ); 
	then		
		//Something sweet riesling or chenin blanc
		WineChooser.userInterface.finishChoosing("2-buck chuck");
		WineChooser.Exchange ex = new WineChooser.Exchange("they rarely have a sense of taste", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q31E" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("What type of special occasion?") && e.getAnswer().equals("New Year's Eve") ); 
	then
    	WineChooser.Exchange ex = new WineChooser.Exchange("New Year's Eve alone?", "");
        ArrayList<String> answers = new ArrayList<>();
    	answers.add("Yes");
    	answers.add("No");
    	WineChooser.userInterface.setAnswers(answers);
		WineChooser.userInterface.setCurrentExchange(ex);
        insert(ex);
end 


rule "Q32A" 
	when								
		e : WineChooser.Exchange(e.getQuestion().equals("First or subsequent") && e.getAnswer().equals("1st") ); 
	then
		WineChooser.userInterface.finishChoosing("california pinor noir");
		WineChooser.Exchange ex = new WineChooser.Exchange("hedonistic joy ridee", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q32B" 
	when			
		e : WineChooser.Exchange(e.getQuestion().equals("First or subsequent") && e.getAnswer().equals("2+") ); 
	then
		WineChooser.userInterface.finishChoosing("complacency is a bitch");
		WineChooser.Exchange ex = new WineChooser.Exchange("merlot", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q33A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is the person old?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("hedonistic joy ride califronia pinot noir", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q33B" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("Is the person old?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("something sweet riesling or chenin blanc", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 


rule "Q34A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("New Year's Eve alone?") && e.getAnswer().equals("Yes") ); 
	then
		WineChooser.userInterface.finishChoosing(null);
		WineChooser.Exchange ex = new WineChooser.Exchange("go for something exotic sangiovese or grenache", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 

rule "Q34A" 
	when
		e : WineChooser.Exchange(e.getQuestion().equals("New Year's Eve alone?") && e.getAnswer().equals("No") ); 
	then
		WineChooser.userInterface.finishChoosing("cheap bubbly spanish cava");
		WineChooser.Exchange ex = new WineChooser.Exchange("", "");
		WineChooser.userInterface.setCurrentExchange(ex);
end 
*/